### ISSUE TITLE
Helm chart installation doesn't show any charts

### ISSUE THREAD

**Issue by ruzickap** [komodorio/helm-charts#147]
I installed the [helm-dashboard](https://github.com/komodorio/helm-dashboard) using the helm chart described here: https://github.com/komodorio/helm-charts/tree/master/charts/helm-dashboard

Unfortunately I do not see any Installed charts:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/1434387/219291982-1375e4ae-3b69-4dc3-84eb-512927cb563a.png">

There are many of them on the cluster which is running [helm-dashboard](https://github.com/komodorio/helm-dashboard):

```bash
❯ helm ls -A                                                                                                                                                       ⎈ mgmt01
NAME                    	NAMESPACE                	REVISION	UPDATED                                	STATUS  	CHART                                                                                   	APP VERSION
aws-ebs-csi-driver      	aws-ebs-csi-driver       	1       	2023-02-16 05:03:57.450296564 +0000 UTC	deployed	aws-ebs-csi-driver-2.17.0                                                               	1.16.0
cert-manager            	cert-manager             	1       	2023-02-16 05:06:25.522097992 +0000 UTC	deployed	cert-manager-v1.11.0                                                                    	v1.11.0
cnpg                    	cnpg-system              	1       	2023-02-16 05:06:55.508180141 +0000 UTC	deployed	cloudnative-pg-0.17.0                                                                   	1.19.0
crossplane              	crossplane-system        	1       	2023-02-16 05:02:28.862560764 +0000 UTC	deployed	crossplane-1.11.0                                                                       	1.11.0
dex                     	dex                      	1       	2023-02-16 05:10:14.121739678 +0000 UTC	deployed	dex-0.13.0                                                                              	2.35.3
external-dns            	external-dns             	1       	2023-02-16 05:07:22.217294821 +0000 UTC	deployed	external-dns-6.13.3
```

There are no other details in the logs:

```bash
❯ kubectl logs -n helm-dashboard helm-dashboard-f94df8567-s6wqq
time="2023-02-16T05:03:23Z" level=info msg="Helm Dashboard by Komodor, version 1.0.0 (none @ unknown)"
time="2023-02-16T05:03:23Z" level=info msg="Got no kubectl config contexts, will attempt to detect if we're inside cluster..."
time="2023-02-16T05:03:23Z" level=warning msg="Newer Helm Dashboard version is available: v1.1.0"
time="2023-02-16T05:03:23Z" level=warning msg="Upgrade instructions: https://github.com/komodorio/helm-dashboard#installing"
time="2023-02-16T05:03:25Z" level=info msg="Discovered Checkov version: 2.1.244"
time="2023-02-16T05:03:25Z" level=info msg="Discovered Trivy: Version: 0.18.3"
time="2023-02-16T05:03:25Z" level=info msg="User analytics is collected to improve the quality, disable it with --no-analytics"
time="2023-02-16T05:03:25Z" level=info msg="Access web UI at: http://0.0.0.0:8080"
[GIN] 2023/02/16 - 05:03:30 | 200 |     136.831µs |      10.0.1.248 | GET      "/status"
...
``` 

I used the following Helm values when installed the `helm-dashboard`:

```yaml
dashboard:
  # allowWriteActions: false
  persistence:
    enabled: false
ingress:
  enabled: true
  className: nginx
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://raw.githubusercontent.com/komodorio/helm-dashboard/9bb597f366426daa2ada06fb87eee2094e862aa3/pkg/dashboard/static/logo.svg"
    forecastle.stakater.com/appName: Helm Dashboard
    nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.${CLUSTER_FQDN}/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.${CLUSTER_FQDN}/oauth2/start?rd=$scheme://$host$request_uri
  hosts:
    - host: helm-dashboard.${CLUSTER_FQDN}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - helm-dashboard.${CLUSTER_FQDN}
```

Any ideas why it is not working?

Thank you
