### ISSUE TITLE
Enable Redact for logs

### ISSUE THREAD

**Issue by sandeebh** [komodorio/helm-charts#293]
I am trying to redact logs and below is what I am using from the documentation [here](https://docs.komodor.com/Learn/Advanced-Configurations.html#:~:text=To%20mask%20passwords%20in%20logs%2C%20apply%20the%20following%20YAML%20configuration%3A)

``` 
    logs:
      namespaceDenylist: ["kube-system"]
      redact:
        - "password=(.+?)\b"
        - "(?U)\"sessionId\": (\".+\"{1})"
```

This gives me the error :

```
Error: INSTALLATION FAILED: YAML parse error on komodor-agent/templates/configmap.yaml: error converting YAML to JSON: yaml: control characters are not allowed
```
any suggestions?
