### ISSUE TITLE
Nginx ingress 404 after deploy

### ISSUE THREAD

**Issue by linonetwo** [komodorio/helm-charts#326]
```
helm repo add komodorio https://helm-charts.komodor.io
helm repo update
helm pull komodorio/helm-dashboard --untar
```

modify value

```yaml
dashboard:
  persistence:
    size: 1000M
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: helm.xxx.site
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - helm.xxx.site
      secretName: "tls-secret"
```

```
helm upgrade --install helm-dashboard ./helm-dashboard --namespace helm-dashboard
kubectl create secret tls tls-secret --cert='/fullchain.cer' --key='/cert.key' -n helm-dashboard
```

Got 404 Not Found nginx after it started.
